// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_APILISTS_REACT_TABLE = "GET_APILISTS_REACT_TABLE";
export const GET_APILIST = "GET_APILIST";
export const DELETE_APILIST = "DELETE_APILIST";
export const DELETE_APILIST_SUCCESS = "DELETE_APILIST_SUCCESS";
export const DELETE_APILIST_FAIL = "DELETE_APILIST_FAIL";
export const ADD_APILIST = "ADD_APILIST";
export const ADD_APILIST_SUCCESS = "ADD_APILIST_SUCCESS";
export const ADD_APILIST_FAIL = "ADD_APILIST_FAIL";
export const UPDATE_APILIST = "UPDATE_APILIST";
export const UPDATE_APILIST_SUCCESS = "UPDATE_APILIST_SUCCESS";
export const UPDATE_APILIST_FAIL = "UPDATE_APILIST_FAIL";
export const SET_APILIST_LOADING_TRUE = "SET_APILIST_LOADING_TRUE";

