// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using WD_ERECORD_CORE.Data;

#nullable disable

namespace WD_ERECORD_CORE.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("\"NormalizedName\" IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("Value")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.AnnouncementList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Label1")
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<string>("Label2")
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("AnnouncementLists");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CostCenterID")
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<string>("CostCenterName")
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<string>("Department")
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<string>("EmployeeType")
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("ManagerId")
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<string>("ManagerName")
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("CLOB");

                    b.Property<string>("ReportChainID")
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Title")
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("\"NormalizedUserName\" IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.CalendarList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("TIMESTAMP");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.HasKey("Id");

                    b.ToTable("CalendarLists");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.CostCenterList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<string>("JobClassificationTrack")
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<string>("JobTitle")
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(150)");

                    b.HasKey("Id");

                    b.ToTable("CostCenterLists");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.DepartmentList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(10)");

                    b.Property<string>("DepartmentDescription")
                        .HasColumnType("VARCHAR2(200)");

                    b.HasKey("Id");

                    b.ToTable("DepartmentLists");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.DocumentCategoryList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(10)");

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("VARCHAR2(200)");

                    b.HasKey("Id");

                    b.ToTable("DocumentCategoryLists");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.EmailGroupList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)");

                    b.HasKey("Id");

                    b.ToTable("EmailGroupLists");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.EmailGroupUserList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<int?>("EmailGroupListId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR2(150)");

                    b.HasKey("Id");

                    b.HasIndex("EmailGroupListId");

                    b.ToTable("EmailGroupUserLists");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.FactoryList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(10)");

                    b.Property<string>("LocationDescription")
                        .HasColumnType("VARCHAR2(200)");

                    b.HasKey("Id");

                    b.ToTable("FactoryLists");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.FormList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<DateTime?>("ExpiredDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("FormData")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("FormDescription")
                        .HasColumnType("VARCHAR2(250)");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<string>("FormRevision")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(20)");

                    b.Property<string>("FormStatus")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<string>("FormSubmittedData")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("GuidelineFile")
                        .HasColumnType("VARCHAR2(250)");

                    b.Property<string>("JSON")
                        .HasColumnType("CLOB");

                    b.Property<string>("MasterFormDetail")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(300)");

                    b.Property<int>("MasterFormId")
                        .HasColumnType("NUMBER(10,0)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<string>("OwnerCostCenter")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(250)");

                    b.Property<string>("OwnerEmailAddress")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(250)");

                    b.Property<int>("RunningNumber")
                        .HasColumnType("NUMBER(10,0)");

                    b.Property<string>("SubmittedBy")
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("UniqueGuidelineFile")
                        .HasColumnType("VARCHAR2(250)");

                    b.HasKey("Id");

                    b.ToTable("FormLists");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.FormListApprovalLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<string>("ApproveCondition")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("EmailReminder")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<int?>("FormListId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("LastSend")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("ReminderType")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("FormListId");

                    b.ToTable("FormListApprovalLevels");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.FormListApprover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("ApproveDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("ApproverEmail")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("ApproverName")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("ApproverStatus")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<int?>("FormListApprovalLevelId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Remark")
                        .HasColumnType("VARCHAR2(250)");

                    b.HasKey("Id");

                    b.HasIndex("FormListApprovalLevelId");

                    b.ToTable("FormListApprovers");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.FormListHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ArchievedDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("FormData")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("FormDescription")
                        .HasColumnType("VARCHAR2(250)");

                    b.Property<int>("FormId")
                        .HasColumnType("NUMBER(10,0)");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<string>("FormRevision")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<string>("FormStatus")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<string>("FormSubmittedData")
                        .HasColumnType("CLOB");

                    b.Property<string>("JSON")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("MasterFormDetail")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(300)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<string>("OwnerCostCenter")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(250)");

                    b.Property<int>("RunningNumber")
                        .HasColumnType("NUMBER(10,0)");

                    b.Property<string>("SubmittedBy")
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("FormListHistories");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.MasterFormCCBApprovalLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<string>("ApproveCondition")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("EmailReminder")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<DateTime?>("LastSend")
                        .HasColumnType("TIMESTAMP");

                    b.Property<int?>("MasterFormDepartmentId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("ReminderType")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("MasterFormDepartmentId");

                    b.ToTable("MasterFormCCBApprovalLevels");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.MasterFormCCBApprover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("ApproveDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("ApproverEmail")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("ApproverName")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("ApproverStatus")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<int?>("MasterFormCCBApprovalLevelId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Remark")
                        .HasColumnType("VARCHAR2(250)");

                    b.HasKey("Id");

                    b.HasIndex("MasterFormCCBApprovalLevelId");

                    b.ToTable("MasterFormCCBApprovers");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.MasterFormDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<int?>("MasterFormListId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)");

                    b.HasKey("Id");

                    b.HasIndex("MasterFormListId");

                    b.ToTable("MasterFormDepartments");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.MasterFormList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("AllowUpRevision")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("AssignedNumberCode")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ChangeLog")
                        .HasColumnType("CLOB");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("CurrentEditor")
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<string>("DocumentCategoryCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<string>("FactoryCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<string>("FormApprovalJSON")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("GuidelineFile")
                        .HasColumnType("VARCHAR2(250)");

                    b.Property<string>("JSON")
                        .HasColumnType("CLOB");

                    b.Property<string>("MasterFormData")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("MasterFormDescription")
                        .HasColumnType("VARCHAR2(250)");

                    b.Property<string>("MasterFormName")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<int>("MasterFormParentId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("MasterFormRevision")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(20)");

                    b.Property<string>("MasterFormStatus")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<string>("OwnerCostCenter")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(250)");

                    b.Property<string>("OwnerEmailAddress")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(250)");

                    b.Property<string>("PermittedDepartments")
                        .HasColumnType("CLOB");

                    b.Property<int>("RunningNumber")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("SubDepartmentCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<string>("SubmittedBy")
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("UniqueGuidelineFile")
                        .HasColumnType("VARCHAR2(250)");

                    b.HasKey("Id");

                    b.ToTable("MasterFormLists");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.MasterFormListHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ArchievedDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("CCBApprovalJSON")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("ChangeLog")
                        .HasColumnType("CLOB");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("JSON")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("MasterFormData")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("MasterFormDescription")
                        .HasColumnType("VARCHAR2(250)");

                    b.Property<int>("MasterFormId")
                        .HasColumnType("NUMBER(10,0)");

                    b.Property<string>("MasterFormName")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<string>("MasterFormRevision")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(20)");

                    b.Property<string>("MasterFormStatus")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<string>("SubmittedBy")
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("MasterFormListHistories");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.PublicLogActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("LogDetail")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(300)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(150)");

                    b.HasKey("Id");

                    b.ToTable("PublicLogActivities");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.PublicLogApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("LogDetail")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(300)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(150)");

                    b.HasKey("Id");

                    b.ToTable("PublicFormApprovals");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.PublicLogEmailNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("LogDetail")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("PublicLogEmailNotifications");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.PublicLogSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("LogDetail")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(300)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(150)");

                    b.HasKey("Id");

                    b.ToTable("PublicLogSystems");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.PublicLogTransferForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("LogDetail")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(1000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(150)");

                    b.HasKey("Id");

                    b.ToTable("PublicLogTransferForms");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.SubDepartmentList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("DepartmentListId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("SubDepartmentCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<string>("SubDepartmentDescription")
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentListId");

                    b.ToTable("SubDepartmentLists");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.SystemRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Name")
                        .HasColumnType("VARCHAR2(250)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("SystemRoles");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.UserManualList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("LatestUpdatedBy")
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<DateTime?>("LatestUpdatedDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("UserManualDescription")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(250)");

                    b.Property<string>("UserManualFilePath")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(250)");

                    b.Property<string>("UserManualName")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(250)");

                    b.HasKey("Id");

                    b.ToTable("UserManualLists");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WD_ERECORD_CORE.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WD_ERECORD_CORE.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WD_ERECORD_CORE.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WD_ERECORD_CORE.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.EmailGroupUserList", b =>
                {
                    b.HasOne("WD_ERECORD_CORE.Data.EmailGroupList", "EmailGroupList")
                        .WithMany("EmailGroupUserLists")
                        .HasForeignKey("EmailGroupListId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("EmailGroupList");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.FormListApprovalLevel", b =>
                {
                    b.HasOne("WD_ERECORD_CORE.Data.FormList", "FormList")
                        .WithMany("FormListApprovalLevels")
                        .HasForeignKey("FormListId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("FormList");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.FormListApprover", b =>
                {
                    b.HasOne("WD_ERECORD_CORE.Data.FormListApprovalLevel", "FormListApprovalLevel")
                        .WithMany("FormListApprovers")
                        .HasForeignKey("FormListApprovalLevelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("FormListApprovalLevel");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.MasterFormCCBApprovalLevel", b =>
                {
                    b.HasOne("WD_ERECORD_CORE.Data.MasterFormDepartment", "MasterFormDepartment")
                        .WithMany("MasterFormCCBApprovalLevels")
                        .HasForeignKey("MasterFormDepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("MasterFormDepartment");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.MasterFormCCBApprover", b =>
                {
                    b.HasOne("WD_ERECORD_CORE.Data.MasterFormCCBApprovalLevel", "MasterFormCCBApprovalLevel")
                        .WithMany("MasterFormCCBApprovers")
                        .HasForeignKey("MasterFormCCBApprovalLevelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("MasterFormCCBApprovalLevel");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.MasterFormDepartment", b =>
                {
                    b.HasOne("WD_ERECORD_CORE.Data.MasterFormList", "MasterFormList")
                        .WithMany("MasterFormDepartments")
                        .HasForeignKey("MasterFormListId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("MasterFormList");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.SubDepartmentList", b =>
                {
                    b.HasOne("WD_ERECORD_CORE.Data.DepartmentList", "DepartmentList")
                        .WithMany("SubDepartmentLists")
                        .HasForeignKey("DepartmentListId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DepartmentList");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.SystemRole", b =>
                {
                    b.HasOne("WD_ERECORD_CORE.Data.ApplicationUser", "ApplicationUser")
                        .WithMany("SystemRoles")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.ApplicationUser", b =>
                {
                    b.Navigation("SystemRoles");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.DepartmentList", b =>
                {
                    b.Navigation("SubDepartmentLists");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.EmailGroupList", b =>
                {
                    b.Navigation("EmailGroupUserLists");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.FormList", b =>
                {
                    b.Navigation("FormListApprovalLevels");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.FormListApprovalLevel", b =>
                {
                    b.Navigation("FormListApprovers");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.MasterFormCCBApprovalLevel", b =>
                {
                    b.Navigation("MasterFormCCBApprovers");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.MasterFormDepartment", b =>
                {
                    b.Navigation("MasterFormCCBApprovalLevels");
                });

            modelBuilder.Entity("WD_ERECORD_CORE.Data.MasterFormList", b =>
                {
                    b.Navigation("MasterFormDepartments");
                });
#pragma warning restore 612, 618
        }
    }
}
